### PR TITLE
Add synchronization to ensure that the integration test repository is only created once

### LINKED ISSUE #7: Method to set up integration test repo cannot be used in multiple test cases that are executed in parallel
K3s sends requests in batches to etcd, and etcd then complains when a creation request for the same resource is included in the same batch, which often happens, when `setup_repository()` is used from multiple test cases that are ran concurrently.

Log shows: 

```
failures:
---- successful_job_should_have_phase_succeeded_and_error_code_0 stdout ----
thread 'successful_job_should_have_phase_succeeded_and_error_code_0' panicked at 'Resource could not be applied: ApiError: etcdserver: duplicate key given in txn request:  (ErrorResponse { status: "Failure", message: "etcdserver: duplicate key given in txn request", reason: "", code: 500 })
Caused by:
    etcdserver: duplicate key given in txn request: ', /home/sliebau/.cargo/git/checkouts/integration-test-commons-88dad6d61b2084fc/ee183a6/src/test/kube.rs:110:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

### PR DESCRIPTION
**Pull request by soenkeliebau**
This should allow running integration tests in parallel again.

fixes #7

### CODE REVIEW

**Comment by soenkeliebau** [comment]
@djc if you want to have a quick look - was unable to pick you as reviewer for some reason

**Comment by djc** [comment]
LGTM (with little knowledge about what the underlying code is actually doing).

**Review by djc — APPROVED** [review]

**Comment by soenkeliebau** [comment]
Thanks Dirkjan, I think this can be considered in a fairly abstract fashion without looking at the actual code that it wraps.

**Comment by soenkeliebau** [comment]
To whomever reviews this - please feel free to merge after reviewing if I am still on vacation :)

**Comment by maltesander** [comment]
Did you test this? 

If you run with multiple threads, each method in one test file is executed in parallel. Therefore in one single file you will apply the crd only once.  

If you run with multiple files, files are executed after each other and setup a new (it is not a real global variable while testing). So for each different file you will apply the crd again.

Thats what you wanted to avoid?

Check that test example:
[playground.tar.gz](https://github.com/stackabletech/integration-test-commons/files/6740575/playground.tar.gz)

**Comment by soenkeliebau** [comment]
I tested it, but only with one file, that is true.

That being said, the objective was to avoid trying to create the crd multiple times _in parallel_ as only this would create issues.

If files are executed consecutively and we can ensure that we only try to create the CRD once per file that is sufficient for our needs - not perfect, but should do the trick.

**Review by maltesander — APPROVED** [review]
LGTM.

**Pull request merged**
